<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.greyshield.com/schema/inventory"
           xmlns:inv="http://www.greyshield.com/schema/inventory"
           elementFormDefault="qualified">

    <xs:element name="components" type="inv:ComponentsType"/>

    <xs:complexType name="ComponentsType">
        <xs:sequence>
            <xs:element name="component" type="inv:ComponentType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ComponentType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="qualityClass" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="supplierRef" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>
